spring:
  application:
    name: export-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: processing-servive
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: '*'
topic:
  completed-event: order.completed.v1
server:
  port: 8081
logging:
  level:
    org.springframework.kafka: DEBUG
    com.orders.processing_servive.kafka.consumer: DEBUG

